---
- name: Environment Start And Stop Playbook
  hosts: all

  tasks:
  - name: Start DB container
    docker_container:
      name: "{{ item.name }}"
      state: started
      image: "{{ item.image }}"
    loop: container_info
    when: inventory_hostname in groups['api']