---
- name: Environment Start And Stop Playbook
  hosts: all
  gather_facts: no

  tasks:
  - name: Start DB container
    docker_container:
      name: "{{ item.name }}"
      state: "{{ container_status }}"
#      image: "{{ item.image }}"
      detach: yes
    loop: "{{ container_info | list }}"
    when: inventory_hostname in groups['db']

  - name: Start API container
    docker_container:
      name: "{{ item.name }}"
      state: "{{ container_status }}"
#      image: "{{ item.image }}"
      detach: yes
    loop: "{{ container_info | list }}"
    when: inventory_hostname in groups['api']